INSERT INTO `tbl_user_priv` (`user_priv_id`, `user_priv_level`, `user_priv_desc`) VALUES
(1, 1, 'Root'),
(2, 2, 'Central Store Admin'),
(3, 3, 'Central Store User'),
(4, 4, 'Store Admin'),
(5, 5, 'Store User'),
(6, 6, 'Purchasing Admin'),
(7, 7, 'Purchasing User'),
(8, 8, 'Finance Admin'),
(9, 9, 'Finance User');


INSERT INTO `tbl_user` (`user_id`, `user_username`, `user_password`, `user_fullname`, `user_level`, `create_by`, `create_date`, `update_by`, `update_date`, `user_store_id`, `user_store_group_id`, `user_img_path`) VALUES
(1, 'admin', 'admin', 'System Administrator', 1, 'system', '2016-03-29', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(2, 'csadmin', 'csadmin', 'Central Store Admin', 2, 'admin', '2016-03-29', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(3, 'csuser', 'csuser', 'Central Store User', 3, 'csadmin', '2016-05-24', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(6, 'procadmin', 'procadmin', 'Procurement Admin', 6, 'csadmin', '2016-05-24', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(8, 'seasonadmin', 'seasonadmin', 'Seasons Restaurant', 4, 'admin', '0000-00-00', NULL, NULL, '2', '2', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(9, 'seasonuser', 'seasonuser', 'Seasons Restaurant', 5, 'admin', '0000-00-00', NULL, NULL, '2', '2', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(10, 'horizonadmin', 'horizonadmin', 'Horizon Admin', 4, 'admin', '2016-05-30', NULL, NULL, '104', '104', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(11, 'horizonuser', 'horizonuser', 'Horizon User', 5, 'admin', '2016-05-30', NULL, NULL, '104', '104', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(14, 'procuser', 'procuser', 'Procurement User', 7, 'admin', '2016-08-08', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(15, 'testuser', 'testuser', 'Test', 4, 'admin', '2016-08-11', NULL, NULL, '130', '130', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(16, 'norlelawati.hassan@rbc.com.bn', 'Centraladmin', 'Dk Norlelawati Pg Hassan', 1, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(17, 'zulfadhli.jali@rbc.com.bn', 'Centraladmin', 'Mohd Zulfadhli Hj Mohd Jali', 1, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(18, 'hamadullah.anwar@rbc.com.bn', 'cs1100', 'Hamad Ullah Bin Anwar', 2, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(19, 'dynastytemp', 'dynastytemp', 'Dysnaty TempStaff', 4, 'admin', '2016-08-11', NULL, NULL, '8', '8', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(20, 'seasontemp', '123', 'Season TempStaff', 4, 'admin', '2016-08-11', NULL, NULL, '2', '2', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(21, 'anjungtemp', 'anjungtemp', 'Anjung Tempstaff', 4, 'admin', '2016-08-11', NULL, NULL, '13', '13', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(22, 'cilantrotemp', 'cilantrotemp', 'Cilantro Tempstaff', 4, 'admin', '2016-08-11', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(23, 'fishcotemp', 'fishcotemp', 'Fish  Co Tempstaff', 4, 'admin', '2016-08-11', NULL, NULL, '7', '7', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(24, 'expresstemp', 'expresstemp', 'Express Tempstaff', 4, 'admin', '2016-08-11', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(25, 'hospitaltemp', 'hospitaltemp', 'Hospital Tempstaff', 4, 'admin', '2016-08-11', NULL, NULL, '9', '9', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(26, 'outsidecateringtemp', 'outsidecateringtemp', 'Outside Catering Tempstaff', 4, 'admin', '2016-08-11', NULL, NULL, '5', '5', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(27, 'hairrandi.japar', 'Centraluser', 'Hairrandi Japar', 2, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(28, 'nurzahidah.pgsuhaili', 'proczahidah', 'Dk Nurzahidah Fikriah Pg Suhaili', 6, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(29, 'bakhtyar.zaini', 'Centraluser', 'Bakhtyar Hj Zaini', 1, 'admin', '2016-08-11', NULL, NULL, '1', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(30, 'razaini.norjamli', 'Centraluser', 'Razaini Norjamli', 3, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(31, 'aminuddin.tuah', 'Centraluser', 'Aminuddin Hj Tuah', 2, 'admin', '2016-08-11', NULL, NULL, '1', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(32, 'muhaimin.mohamad', 'Centraluser', 'Muhaimin Mohamad', 3, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(33, 'izzati.rahman', 'Centraluser', 'Siti Nurul Adli Izzati Hj Abd Rahman', 7, 'admin', '2016-08-11', NULL, NULL, '79', '79', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(34, 'lim.guan', 'centraluser', 'Lim Soon Guan', 3, 'admin', '2016-08-11', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(35, 'seasonkitchen', 'seasonkitchen', 'Season Kitchen', 5, 'admin', '2016-08-12', NULL, NULL, '2', '2', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(36, 'dynasty restaurant', 'dynasty123', 'Dynasty Restaurant ', 4, 'admin', '2016-08-15', NULL, NULL, '8', '8', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(37, 'dynasty restaurant kitchen', 'dynasty123!', 'Dynasty Restaurant Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '8', '8', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(38, 'season restaurant', 'season123', 'Season Restaurant', 4, 'admin', '2016-08-15', NULL, NULL, '2', '2', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(39, 'season restaurant kitchen', 'season123!', 'Season Restaurant Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '2', '2', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(40, 'fish & co service', 'fishcoservices', 'Fish & Co Service', 5, 'admin', '2016-08-15', NULL, NULL, '7', '7', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(41, 'fish & co kitchen', 'fishcokitchen', 'Fish & Co Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '7', '7', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(42, 'fish & co ', 'fishco123', 'Fish & Co Admin', 4, 'admin', '2016-08-15', NULL, NULL, '7', '7', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(43, 'anjung saujana service', 'anjungservice', 'Anjung Saujana Service', 5, 'admin', '2016-08-15', NULL, NULL, '13', '13', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(44, 'anjung saujana kitchen', 'anjungkitchen', 'Anjung Saujana Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '13', '13', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(45, 'anjung saujana ', 'anjung123', 'Anjung Saujana Admin', 4, 'admin', '2016-08-15', NULL, NULL, '13', '13', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(46, 'cilantro service', 'cilantroservice', 'Cilantro Service', 5, 'admin', '2016-08-15', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(47, 'cilantro kitchen', 'cilantrokitchen', 'Cilantro Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(48, 'cilantro', 'cilantro123', 'Cilantro Admin', 4, 'admin', '2016-08-15', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(49, 'outside catering', 'outside123', 'Outside Catering Admin', 4, 'admin', '2016-08-15', NULL, NULL, '5', '5', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(50, 'outside catering kitchen', 'outsidekitchen', 'Outside Catering Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '5', '5', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(51, 'aircraft catering admin', 'aircraftadmin', 'Aircraft Catering Admin', 4, 'admin', '2016-08-15', NULL, NULL, '4', '4', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(52, 'aircraft operation', 'aircraftoperation', 'Aircraft Operation', 5, 'admin', '2016-08-15', NULL, NULL, '4', '4', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(53, 'aircraft inflight store', 'inflightstore', 'Aircraft Inflight Store', 5, 'admin', '2016-08-15', NULL, NULL, '4', '4', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(54, 'flight kitchen admin', 'flightkitchen', 'Flight Kitchen Admin', 5, 'admin', '2016-08-15', NULL, NULL, '4', '4', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(55, 'horizon', 'horizon123', 'Horizon Admin', 4, 'admin', '2016-08-15', NULL, NULL, '3', '3', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(56, 'horizon kitchen', 'horizonkitchen', 'Horizon Kitchen', 5, 'admin', '2016-08-15', NULL, NULL, '3', '3', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(57, 'atiqah.matnor', 'Admin123!', 'Atiqah Matnor', 1, 'admin', '2016-08-18', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(58, 'bakery', 'bakery123', 'Bakery', 4, 'admin', '2016-09-02', NULL, NULL, '131', '131', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(59, 'butchery', 'butchery123', 'Butchery', 4, 'admin', '2016-09-02', NULL, NULL, '132', '132', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(60, 'cold.kitchen', 'cold123', 'Cold Kitchen', 4, 'admin', '2016-09-02', NULL, NULL, '133', '133', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(61, 'hot.kitchen', 'hot123', 'Hot Kitchen', 4, 'admin', '2016-09-02', NULL, NULL, '134', '134', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(62, 'flight.canteen', 'canteen123', 'FLIGHT KITCHEN STAFF CANTEEN', 4, 'admin', '2016-09-02', NULL, NULL, '14', '14', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(63, 'sky.lounge', 'sky123', 'SKY LOUNGE', 4, 'admin', '2016-09-02', NULL, NULL, '26', '26', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(64, 'mof.kitchen', 'mof123', 'MOF CAFETERIA KITCHEN', 4, 'admin', '2016-09-02', NULL, NULL, '541', '541', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(65, 'mof.kitchen', 'mof123', 'MOF CAFETERIA KITCHEN', 4, '', '2016-09-03', NULL, NULL, '541', '541', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(67, 'muna.hamzah', 'ProcMuna', 'Siti Munawarah Binti Ali Hamzah', 1, 'atiqah.matnor', '2016-09-07', NULL, NULL, '79', '79', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(68, 'dinie.azman', 'ProcDinie', 'Ak Md Dinie Hafizuddin Bin Pg Azman', 7, 'atiqah.matnor', '2016-09-07', NULL, NULL, '79', '79', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(69, 'bazilah.saidin', 'ProcBazilah', 'Hamizah Bazilah Bte Haji Saidin', 1, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(70, 'amieza.rashidie', 'ProcAmieza', 'Nuramieza Binti Rashidie', 7, 'atiqah.matnor', '2016-09-07', NULL, NULL, '79', '79', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(71, 'john.lim', 'Dynastyadmin', 'John Faraon Lim', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '101', '101', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(72, 'jesse.icban', 'dYNASTYADMIN', 'Jesse Yandan Icban', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '602', '602', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(73, 'keen.wai', 'Dynastyadmin', 'Chong Keen Wai', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1011', '1011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(74, 'teck.hong', 'dYNASTYADMIN', 'Kong Teck Hong', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1011', '1011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(75, 'rosli.metassan', 'Seasonsadmin', 'Rosli Bin Metassan', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '102', '102', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(76, 'ahmad.mahlel', 'Seasonsadmin', 'Ahmad Bin Mahlel', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '102', '102', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(77, 'masri.hassan', 'Seasonsadmin', 'Masri Bin Hassan', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1021', '1021', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(78, 'zaidi.ahmad', 'Seasonsadmin', 'Ak Zaidi Bin Pg Ahmad', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1021', '1021', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(79, 'oscar.abrera', 'Horizonadmin', 'Oscar C Abrera', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '104', '104', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(80, 'munirah.hassan', 'Horizonadmin', 'Siti Munirah Binti Hj Hassan', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '104', '104', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(81, 'maria.morata', 'Horizonuser', 'Maria Czarina H Morata', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '104', '104', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(83, 'wong.min', 'Horizonadmin', 'Wong Ka Min', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1041', '1041', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(84, 'reduan.ahmad', 'Horizonuser', 'Mohd Reduan Bin Ahmad', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1041', '1041', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(85, 'asrol.duraman', 'Seasonsadmin', 'Hj Asrol Bin Duraman', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1021', '1021', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(87, 'azmi.aziz', 'ACCadmin', 'Mohammad Azmi Bin Hj Abd Aziz', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(88, 'zamir.dollah', 'ACCuser', 'Zamir Bin Hj Dollah', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(89, 'suwardi.safar', 'ACCuser', 'Suwardi Bin Hj Safar', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(90, 'khalillah.ariffin', 'ACCuser', 'Siti Khalillah Binti Hj Ariffin', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(91, 'edah.hamid', 'ACCuser', 'Hjh Edahwati Binti Hj Abd Hamid', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(92, 'wazien.norhalim', 'Aoadmin', 'Muhammad Wazien Bin Hj Norhalim', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(93, 'norlela.mejenis', 'Aouser', 'Norlela Binti Hj Mejenis', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(94, 'zaiton.ali', 'Aouser', 'Hjh Zaiton Binti Ali', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(95, 'matassim.juddin', 'Aouser', 'Hj Matassim Bin Hj Juddin', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(96, 'saparudin.abidin', 'Aouser', 'Hj Saparudin Bin Hj Abidin', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(97, 'suhaimi.ali', 'Aouser', 'Suhaimi Bin Hj Mohd Ali', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(98, 'sani.zaidi', 'Aoadmin', 'Pg Hj Sani Bin Pg Hj Zaidi', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(99, 'nurul.chua', 'Aoadmin', 'Siti Nurul Shafiqah Binti Abdullah Chua', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(100, 'zafari.damit', 'Aouser', 'Pg Zafari Bin Pg Hj Damit', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(101, 'norlia.maidin', 'Aouser', 'Norlia Binti Maidin', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(102, 'puasa.ahmad', 'Aouser', 'Puasa Bin Ahmad', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(103, 'aminuddin.mohammad', 'Aouser', 'Ak Aminuddin Bin Pg Hj Mohammad', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '12', '12', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(104, 'yip.lee', 'horizonadmin', 'Yip Soon Lee', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '270', '270', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(105, 'saifullah.tay', 'Assuser', 'Muhammad Saifullah Bin Abdullah Tay', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '270', '270', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(106, 'rosli.aman', 'Askadmin', 'Rosli Bin Che Aman', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '271', '271', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(107, 'johari.hamid', 'Askadmin', 'Johari Bin Abdul Hamid', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '271', '271', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(108, 'samliwati.damit', 'Askadmin', 'Samliwati Binti Hj Awg Damit', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '271', '271', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(109, 'mahani.tajuddin', 'Fkadmin', 'Dk Mahani Binti Pg Hj Tajuddin', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '130', '130', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(110, 'fairuzi.nanyan', 'Fkadmin', 'Fairuzi Bin Nanyan', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '130', '130', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(111, 'fikri.rahman', 'Fkuser', 'Mohammad Fikri Bin Hj Abdul Rahman', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '130', '130', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(112, 'nortini.salleh', 'Bakeryuser', 'Nortini Binti Mat Salleh', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '131', '131', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(113, 'chang.khiong', 'Bakeryadmin', 'Chang Chee Khiong', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '131', '131', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(114, 'don.zain', 'Bakeryuser', 'Mohammad Don Bin Hj Mohammad Zain', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '131', '131', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(115, 'ahmad.mangsor', 'Bakeryadmin', 'Ahmad Bin Hj Mangsor', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '131', '131', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(116, 'rosli.amir', 'Butcheryadmin', 'Rosli Bin Amir', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '132', '132', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(117, 'sofiandy.mahadi', 'Ckuser', 'Sofiandy Bin Hj Mahadi', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '133', '133', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(118, 'andy.chong', 'Ckadmin', 'Andy Chong Kai Siong', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '133', '133', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(119, 'azizi.tinggi', 'Butcheryuser', 'Mohammad Amirul Azizi Bin Abdullah Tinggi', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '132', '132', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(120, 'azidah.abdullah', 'Ckuser', 'Hjh Nur Azidah Binti Abdullah', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '133', '133', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(121, 'rusdi.ilyas', 'Hkuser', 'Rusdi Bin Ilyas', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '134', '134', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(123, 'zarin.tinggi', 'Hkuser', 'Mohd Zarin Bin Abdullah Tinggi', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '134', '134', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(124, 'harris.yusmalek', 'Ocadmin', 'Abdul Harris Yusmalek', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '25', '25', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(125, 'ashley.jeffre', 'MOFadmin', 'Achmed Ashley Bin Jeffre', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '54', '54', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(126, 'rafie.abdullah', 'Ocadmin', 'Ronaldo Natividad Villafuerte@Muhd Raf', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '25', '25', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(127, 'sri.johari', 'Seasonsadmin', 'Sri Rohaya Binti Hj Johari', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '1021', '1021', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(128, 'djoko.pramono', 'Ocuser', 'Djoko Dwi Pramono', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '25', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(129, 'salbiah.bakar', 'Ripasadmin', 'Salbiah Binti Awg Hj Bakar', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6002', '6002', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(131, 'marlini.lefmin', 'Ripasuser', 'Marlini Binti Hj Lefmin', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6002', '6002', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(133, 'jimmy.chai', 'Ripasadmin', 'Jimmy Chai', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6004', '6004', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(134, 'normah.talip', 'Ripasadmin', 'Siti Normah Binti Hj Talip', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6002', '6004', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(137, 'adam.shaib', 'Laundryadmin', 'Muhammad Adam Malek Bin Abdul Shaib', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '91', '91', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(138, 'norsham.othman', 'Kiulapadmin', 'Norsham Binti Hj Othman', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '66', '66', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(139, 'dwarni.jawi', 'Kiulapadmin', 'Dwarni Binti Mohd Jawi', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '66', '66', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(140, 'hkadmin', 'Hkadmin', 'Michael Chin Yuk Fatt', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '134', '134', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(141, 'nurizzat.mokti', 'Fcuser', 'Muhd Nurizzat Ifwat Bin Hj Mokti', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '3011', '3011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(142, 'faizal.mohammad', 'Fcadmin', 'Mohammad Faizal Bin Mohammad', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '3011', '3011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(143, 'fatmawati.muhammad', 'PMOadmin', 'Fatmawati Binti Hj Muhammad', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '602', '602', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(144, 'rahman.bahir', 'dyadmin', 'Abd Rahman Bin Hj Bahir', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '101', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(145, 'jusni.salleh', 'Tutongadmin', 'Hj Jusni Bin Salleh', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6041', '6041', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(146, 'sharifuddin.tahiruddin', 'JPMCuser', 'Sharifuddin Bin Hj Tahiruddin', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '65', '65', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(147, 'randy.jeffrey', 'JPMCadmin', 'Randy Bin Jeffrey', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '65', '65', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(148, 'sabariya.salleh', 'JPMCadmin', 'Hjh Sabariya Binti Haji Salleh', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6031', '1500', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(149, 'nohan.hamid', 'JPMCadmin', 'Mohd Nohan Bin Abd Hamid', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6031', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(150, 'karim.rahim', 'JPMCadmin', 'Muhammad Abdul Karim Bin Abdul Rahim', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '603', '603', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(151, 'nenita.dignadice', 'JPMCuser', 'Nenita S Dignadice', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6032', '6032', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(152, 'fevian.abidin', 'JPMCadmin', 'Muhammad Fevian Bin Zainal Abidin', 4, 'atiqah.matnor', '2016-09-07', NULL, NULL, '6032', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(153, 'suzana.rosli', 'Tutonguser', 'Dk Suzana Binti Pg Rosli', 5, 'atiqah.matnor', '2016-09-07', NULL, NULL, '604', '604', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(155, 'foh.kuet', 'Dynastyuser', 'Jong Foh Kuet', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '1011', '1011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(156, 'jublinah.awang', 'Dynastyuser', 'Siti Jublinah@Noor Rafidah Bte Awang', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '1011', '1011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(157, 'enrico.talens', 'Dynastyuser', 'Enrico T Talens', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '101', '101', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(158, 'roziman.ismail', 'Horizonuser', 'Mohammad Roziman Bin Haji Ismail', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '104', '104', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(159, 'edy.lau', 'Horizonuser', 'Edy Lau', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '1041', '1041', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(160, 'hengky.ku', 'Horizonuser', 'Hengky Ku', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '1041', '1041', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(161, 'afida.jalil', 'Askuser', 'Farina Afida Bte Pehin Hj Abd Jalil', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '271', '271', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(162, 'hafizah.harith', 'Fcuser', 'Hjh Norhafizah Bte Hj Harith', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '3011', '3011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(163, 'yazid.yusof', 'Fcuser', 'Yazid Bin Hj Yusof', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '3011', '3011', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(164, 'fared.manshordin', 'Ripasadmin', 'Mohamad Fared Bin Manshordin', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '6004', '6004', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(165, 'ariffin.kassim', 'Assadmin', 'Ariffin Bin Hj Kassim/Ismail', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '270', '270', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(167, 'noriah.wahab', 'Kiulapadmin', 'Noriah Bte Hj Abd Wahab', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '66', '66', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(168, 'elvin.chiang', 'Fcadmin', 'Elvin Lim Leong Chiang', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '3010', '3010', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(170, 'rafie.magno', 'Fcuser', 'Rafie A.Magno', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '3010', '3010', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(172, 'sediah.samail', 'JPMCuser', 'Sediah Bte Hj Samail', 5, 'atiqah.matnor', '2016-09-26', NULL, NULL, '603', '603', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(173, 'suyanto', 'Assuser', 'Suyanto', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '270', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(175, 'sabariya.salleh', 'admin123', 'Hjh Sabariya Binti Haji Salleh', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '604', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(176, 'masri.hassan', 'Ocadmin', 'Masri Bin Hassan', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '25', '25', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(177, 'masri.hassan', 'MOFadmin', 'Masri Bin Hassan', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '54', '54', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(178, 'masri.hassan', 'PMOadmin', 'Masri Bin Hassan', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '602', '602', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(179, 'zaidi.ahmad', 'Ocadmin', 'Ak Zaidi Bin Pg Ahmad', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '25', '25', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(180, 'zaidi.ahmad', 'MOFadmin', 'Ak Zaidi Bin Pg Ahmad', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '54', '54', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(181, 'zaidi.ahmad', 'PMOadmin', 'Ak Zaidi Bin Pg Ahmad', 4, 'atiqah.matnor', '2016-09-26', NULL, NULL, '602', '602', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(182, 'judy.chong', 'Ajgndc69', 'Judy Chong Mei Yun', 1, 'atiqah.matnor', '2016-09-26', NULL, NULL, '1', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(183, 'aliza.menuddin', 'FINANCEadmin', 'Aliza Binti Menuddin', 8, 'atiqah.matnor', '2016-09-26', NULL, NULL, '71', '71', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(184, 'member.endit', 'MOFadmin', 'Member Ak Endit', 4, 'atiqah.matnor', '2016-09-28', NULL, NULL, '54', '54', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(185, 'hafiz.morsidi', 'Financeuser', 'Hj Muhammad Hafiz Bin Hj Morsidi', 9, 'atiqah.matnor', '2016-09-28', NULL, NULL, '71', '71', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(186, 'ismawati.ismail', 'Tutonguser', 'Ismawati Binti Hj Ismail', 4, 'atiqah.matnor', '2016-09-29', NULL, NULL, '604', '604', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(187, 'zulina.ali', 'Dryadmin', 'Zulina Binti Hj Mohd Ali', 4, 'atiqah.matnor', '2016-09-29', NULL, NULL, '8', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(188, 'sofian.matarsat', 'Dryuser', 'Pg Sofian Bin Pg Hj Matarsat', 5, 'atiqah.matnor', '2016-09-29', NULL, NULL, '8', '8', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(189, 'sofrizal.masri', 'Dryuser', 'Sofrizal Bin Hj Masri', 4, 'atiqah.matnor', '2016-09-29', NULL, NULL, '8', '8', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(190, 'armah.tahir', 'Kiulapuser', 'Siti Armah Binti Tahir', 5, 'atiqah.matnor', '2016-10-04', NULL, NULL, '66', '66', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(191, 'sita.matassan', 'Kiulapuser', 'Sita Binti Matassan', 5, 'atiqah.matnor', '2016-10-04', NULL, NULL, '66', '66', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(192, 'alvin.voon', 'accadmin', 'Alvin Voon', 4, 'atiqah.matnor', '2016-10-04', NULL, NULL, '11', '11', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(193, 'arifazri.sabtu', 'Arifazri610249', 'Mohd Arifazri Bin Sabtu', 1, 'atiqah.matnor', '2016-10-05', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(194, 'shokrin.rahman', 'Ripasadmin', 'Hj Shokrin Bin Abdul Rahman', 4, 'arifazri.sabtu', '2016-10-05', NULL, NULL, '6004', '6004', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(195, 'zunaidah.zania', 'Ripasuser', 'Zunaidah Binti Hj Zania', 5, 'arifazri.sabtu', '2016-10-05', NULL, NULL, '6002', '6002', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(196, 'marhain.matzain', 'Assadmin', 'Marhain Binti Hj Mat Zain', 4, 'atiqah.matnor', '2016-10-05', NULL, NULL, '270', '270', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(198, 'michael.fatt', 'Hkadmin', 'Michael Fatt', 4, 'atiqah.matnor', '2016-10-06', NULL, NULL, '134', '134', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(200, 'shamsir.sani', 'Asadmin', 'Mohd Shamsir Bin Mohd Sani', 4, 'atiqah.matnor', '2016-10-07', NULL, NULL, '270', '270', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(201, 'saadah.edin', 'csadmin', 'Nur Daneesaadah Binti Abdullah Edin', 2, 'atiqah.matnor', '2016-10-10', NULL, NULL, '1', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(202, 'zabaidah.arshad', 'Fnbadmin', 'Dk Zabaidah Binti Pg Arshad', 4, 'atiqah.matnor', '2016-10-10', NULL, NULL, '85', '85', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(203, 'muna.osman', 'ABC1234', 'Hjh Siti Munawwarah Binti Osman', 1, 'atiqah.matnor', '2016-10-11', NULL, NULL, '79', '79', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(205, 'ajar.jumat', 'RIPASuser', 'Ajar Binti Hj Jumat', 4, 'atiqah.matnor', '2016-10-11', NULL, NULL, '6004', '6004', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(206, 'ratna.abdullah', 'MISadmin', 'Hjh Ratna Dewi Binti Abdullah', 1, 'atiqah.matnor', '2016-10-13', NULL, NULL, '1', '1', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(207, 'christine.chan', 'rbc12345', 'Christine Chan', 1, 'atiqah.matnor', '2016-10-14', NULL, NULL, '1', '0', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(209, 'masni.samat', 'RIPASadmin', 'Hjh Masni Binti Hj Samat', 4, 'atiqah.matnor', '2016-10-19', NULL, NULL, '6002', '6002', 'images/icon-driveway-paving-braintree-weymouth-quincy-ma.png'),
(211, 'hcd', 'hcdadmin', 'Hcd', 4, 'atiqah.matnor', '2016-11-28', NULL, NULL, '72', '72', 'images/'),
(212, 'ainoreen.sahrin', 'STOREadmin', 'Mohammad Ainoreen Bin Sahrin', 3, 'arifazri.sabtu', '2016-12-14', NULL, NULL, '75', '75', 'images/'),
(213, 'outlet', 'outlet', 'Outlet Store Testing Account', 4, 'admin', '2016-12-15', NULL, NULL, '102', '0', 'images/'),
(214, 'outlet kitchen', 'outlet', 'Kitchen', 5, 'admin', '2016-12-15', NULL, NULL, '102', '102', 'images/'),
(215, 'zul.tom', 'ADMINstore', 'Zulfadhli Bin Tom', 2, 'arifazri.sabtu', '2016-12-19', NULL, NULL, '1', '1', 'images/'),
(216, 'hazim.jaini', 'centraladmin', 'Muhammad Hazim Bin Jaini', 2, 'arifazri.sabtu', '2016-12-19', NULL, NULL, '1', '1', 'images/'),
(217, 'faridah.teo', 'admincentral!!123', 'Faridah Teo Abdullah', 1, 'arifazri.sabtu', '2016-12-19', NULL, NULL, '1', '0', 'images/'),
(218, 'maswati.ahmad', '81171', 'Maswati Hj Ahmad', 8, 'atiqah.matnor', '2017-01-11', NULL, NULL, '71', '0', 'images/'),
(219, 'radziah.sarbini', 'Vinc7313', 'Radziah Sarbini', 1, 'atiqah.matnor', '2017-01-11', NULL, NULL, '1', '0', 'images/'),
(220, 'hjhafiz.morsidi@rbc.com.bn', 'Hjhafiz07041991', 'HAJI MUHAMMAD HAFIZ BIN HAJI MORSIDI', 8, 'atiqah.matnor', '2017-01-11', NULL, NULL, '71', '0', 'images/'),
(221, 'elvin.lim', 'magnumadmin', 'Elvin Lim', 4, 'atiqah.matnor', '2017-01-11', NULL, NULL, '3013', '3000', 'images/'),
(222, 'katrina', 'magnumadmin', 'Katrina', 4, 'atiqah.matnor', '2017-01-11', NULL, NULL, '3013', '0', 'images/'),
(223, 'faizal', 'magnumadmin', 'Faizal', 4, 'atiqah.matnor', '2017-01-11', NULL, NULL, '3013', '3000', 'images/'),
(224, 'majidah', 'magnumuser', 'Majidah', 5, 'atiqah.matnor', '2017-01-11', NULL, NULL, '3013', '0', 'images/'),
(226, 'khuzaimah.bakir', 'lsadmin', 'Khuzaimah Bte Hj Bakir', 4, 'atiqah.matnor', '2017-01-16', NULL, NULL, '069', '069', 'images/'),
(228, 'noni.hamid', 'lsadmin', 'Noni Yusrinawati Abdul Hamid', 4, 'atiqah.matnor', '2017-01-16', NULL, NULL, '069', '069', 'images/'),
(229, 'mila.jumat', 'lsadmin', 'Milawati Jumat', 4, 'atiqah.matnor', '2017-01-16', NULL, NULL, '069', '069', 'images/'),
(230, 'asyidah.abdullah', 'csuser', 'Nurasyidah Abdullah', 3, 'atiqah.matnor', '2017-01-17', NULL, NULL, '1', '1', 'images/'),
(231, 'hafizul.hassan', 'csuser', 'Mohd Hafizulyahya Hassan', 3, 'atiqah.matnor', '2017-01-17', NULL, NULL, '1', '1', 'images/'),
(232, 'noorsaibah.mohiddin', 'Sns747177', 'SITI NOOR SAIBAH BINTI HJ MOHIDDIN', 8, 'atiqah.matnor', '2017-01-17', NULL, NULL, '71', '0', 'images/'),
(233, 'ayub', 'pmoadmin', 'Hj Mohamad Ayub', 4, 'atiqah.matnor', '2017-01-25', NULL, NULL, '602', '602', 'images/'),
(234, 'afiqah.marali', 'lsadmin', 'Afiqah Marali', 4, 'atiqah.matnor', '2017-01-26', NULL, NULL, '069', '069', 'images/'),
(235, 'johana.sahat', 'beauty1970', 'Johana Sahat', 8, 'atiqah.matnor', '2017-01-31', NULL, NULL, '71', '71', 'images/'),
(236, 'wafiuddin.sukur', 'csuser', 'Wafiuddin Hj Sukar', 3, 'atiqah.matnor', '2017-02-01', NULL, NULL, '1', '0', 'images/'),
(237, 'raizani.norjamli', 'csuser', 'Raizani Norjamli', 3, 'atiqah.matnor', '2017-02-01', NULL, NULL, '1', '1', 'images/'),
(238, 'andy.ching', '3421', 'Andy Ching Kian Hoe', 8, 'atiqah.matnor', '2017-02-16', NULL, NULL, '71', '71', 'images/'),
(239, 'seriemma.jemat', 'rbc12345', 'Seri Emma Sulastri', 1, 'arifazri.sabtu', '2017-03-29', NULL, NULL, '75', '0', 'images/'),
(240, 'amalaqilah.ariffin', 'rbc12345', 'Amal Aqilah Ariffin', 1, 'arifazri.sabtu', '2017-03-29', NULL, NULL, '75', '75', 'images/');