INSERT INTO `tbl_store` (`store_id`, `store_name`, `store_address`, `store_desc`) VALUES
('069', 'RBC Lifestyle', ' ', ' '),
('1', 'Central Store', '', 'Central Store'),
('10', 'Kak Ros', NULL, NULL),
('10030', 'Magnum', ' ', ' '),
('101', 'Dynasty Restaurant', NULL, NULL),
('1011', 'Dynasty Restaurant Kitchen', NULL, NULL),
('102', 'Seasons Restaurant', NULL, NULL),
('1021', 'Seasons Restaurant Kitchen', NULL, NULL),
('104', 'Horizon', NULL, NULL),
('1041', 'Horizon Kitchen', NULL, NULL),
('11', 'Aircraft Catering Admin', NULL, NULL),
('12', 'Aircraft Operation', NULL, NULL),
('122', 'Aircraft Inflight Store', NULL, NULL),
('13', 'Anjung Saujana', NULL, NULL),
('130', 'Flight Kitchen Admin', NULL, NULL),
('131', 'Bakery', NULL, NULL),
('132', 'Butchery', NULL, NULL),
('133', 'Cold Kitchen', NULL, NULL),
('134', 'Hot Kitchen', NULL, NULL),
('14', 'Flight Kitchen Staff Canteen', NULL, NULL),
('2', 'Seasons Restaurant', NULL, NULL),
('25', 'Outside Catering', NULL, NULL),
('2501', 'Outside Catering Kitchen', NULL, NULL),
('26', 'Sky Lounge', NULL, NULL),
('270', 'Anjung Saujana Service', NULL, NULL),
('271', 'Anjung Saujana  Kitchen', NULL, NULL),
('280', 'Cilantro Service', NULL, NULL),
('281', 'Cilantro Kitchen', NULL, NULL),
('3', 'The Horizons', NULL, NULL),
('3010', 'Fish & Co Service', NULL, NULL),
('3011', 'Fish & Co Kitchen', NULL, NULL),
('3013', 'Magnum Service', ' ', ' '),
('3014', 'Magnum Kitchen', ' ', ' '),
('4', 'Aircraft Catering Centre', NULL, NULL),
('5', 'Restaurant & Outside Catering', NULL, NULL),
('54', 'MOF Cafeteria', NULL, NULL),
('541', 'MOF Cafeteria Kitchen', NULL, NULL),
('6', 'Mc Donald\'s Brunei', NULL, NULL),
('600', 'RIPAS Hospital Catering', NULL, NULL),
('6001', 'RIPAS Admin', NULL, NULL),
('6002', 'RIPAS Services', NULL, NULL),
('6003', 'RIPAS Operations', NULL, NULL),
('6004', 'RIPAS Kitchen', NULL, NULL),
('602', 'PMO Canteen', NULL, NULL),
('6021', 'PMO Canteen Kitchen', NULL, NULL),
('603', 'JPMC/TBCC Services', NULL, NULL),
('6031', 'JPMC/TBCC Kitchen/Production', '', ' '),
('6032', 'JPMC Cafe Service', NULL, NULL),
('6033', 'JPMC Cafe Kitchen', NULL, NULL),
('604', 'Tutong Hospital', NULL, NULL),
('6041', 'Tutong Hospital Kitchen\r\n', NULL, NULL),
('64', 'JPMC Admin', ' ', ' '),
('65', 'JPMC Kitchen', ' ', ' '),
('66', 'Kiulap Express', NULL, NULL),
('7', 'Fish & Co Brunei', NULL, NULL),
('71', 'Finance', NULL, NULL),
('72', 'Human Capital Development Dept', NULL, NULL),
('75', 'Store Dept', NULL, NULL),
('79', 'Procurement Department', NULL, NULL),
('8', 'Dry Store', '', ''),
('80', 'General Manager Department', NULL, NULL),
('802', 'Asset Management', NULL, NULL),
('83', 'Management Information System', NULL, NULL),
('84', 'Product Innovation Dept', NULL, NULL),
('841', 'Sales & Marketing Department', NULL, NULL),
('85', 'Food & Beverage Admin Dept.', NULL, NULL),
('86', 'Quality Assurance', NULL, NULL),
('9', 'Institutional Hospital Catering', NULL, NULL),
('91', 'Laundry Department', NULL, NULL);


INSERT INTO `tbl_store_group` (`store_group_id`, `store_group_store_id`, `store_group_name`) VALUES
('11', '11', 'Aircraft Catering Admin'),
('4', '4', 'Aircraft Catering Centre'),
('122', '122', 'Aircraft Inflight Store'),
('12', '12', 'Aircraft Operation'),
('13', '13', 'Anjung Saujana'),
('271', '271', 'Anjung Saujana  Kitchen'),
('270', '270', 'Anjung Saujana Service'),
('802', '802', 'Asset Management'),
('131', '131', 'Bakery'),
('132', '132', 'Butchery'),
('1', '1', 'Central Store'),
('281', '281', 'Cilantro Kitchen'),
('280', '280', 'Cilantro Service'),
('133', '133', 'Cold Kitchen'),
('8', '8', 'Dry Store'),
('101', '101', 'Dynasty Restaurant'),
('1011', '1011', 'Dynasty Restaurant Kitchen'),
('71', '71', 'Finance'),
('7', '7', 'Fish & Co Brunei'),
('3011', '3011', 'Fish & Co Kitchen'),
('3010', '3010', 'Fish & Co Service'),
('130', '130', 'Flight Kitchen Admin'),
('14', '14', 'Flight Kitchen Staff Canteen'),
('85', '85', 'Food & Beverage Admin Dept.'),
('80', '80', 'General Manager Department'),
('104', '104', 'Horizon'),
('1041', '1041', 'Horizon Kitchen'),
('134', '134', 'Hot Kitchen'),
('72', '72', 'Human Capital Development Dept'),
('9', '9', 'Institutional Hospital Catering'),
('64', '64', 'JPMC Admin'),
('6033', '6033', 'JPMC Cafe Kitchen'),
('6032', '6032', 'JPMC Cafe Service'),
('65', '65', 'JPMC Kitchen'),
('6031', '6031', 'JPMC/TBCC KItchen/Production'),
('603', '603', 'JPMC/TBCC Services'),
('10', '10', 'Kak Ros'),
('66', '66', 'Kiulap Express'),
('91', '91', 'Laundry Department'),
('83', '83', 'Management Information System'),
('6', '6', 'Mc Donald\'s Brunei'),
('54', '54', 'MOF Cafeteria'),
('541', '541', 'MOF Cafeteria Kitchen'),
('25', '25', 'Outside Catering'),
('2501', '2501', 'Outside Catering Kitchen'),
('602', '602', 'PMO Canteen'),
('6021', '6021', 'PMO Canteen Kitchen'),
('79', '79', 'Procurement Department'),
('84', '84', 'Product Innovation Dept'),
('86', '86', 'Quality Assurance'),
('5', '5', 'Restaurant & Outside Catering'),
('6001', '6001', 'RIPAS Admin'),
('600', '600', 'RIPAS Hospital Catering'),
('6004', '6004', 'RIPAS Kitchen'),
('6003', '6003', 'RIPAS Operations'),
('6002', '6002', 'RIPAS Services'),
('841', '841', 'Sales & Marketing Department'),
('2', '2', 'Seasons Restaurant'),
('102', '102', 'Seasons Restaurant'),
('1021', '1021', 'Seasons Restaurant Kitchen'),
('26', '26', 'Sky Lounge'),
('75', '75', 'Store Dept'),
('3', '3', 'The Horizons'),
('604', '604', 'Tutong Hospital'),
('6041', '6041', 'Tutong Hospital Kitchen'),
('1500', '64', 'JPMC Group'),
('10030', '10030', 'Magnum'),
('069', '069', 'RBC Lifestyle');